name: Release Maven Project

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
      developmentVersion:
        description: 'Next development version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Necessary for maven-release-plugin to access all history

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configure Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Release
      run: mvn release:prepare -B -X \ 
          -DreleaseVersion=1.0 -DdevelopmentVersion=1.1-SNAPSHOT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

